on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    env:
      RepositoryUrl: https://github.com/${{ github.repository }}
      source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      version: 0.0.0-g${{ github.sha }}

    steps:
    - run: dotnet new console

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x' # SDK Version to use.
        source-url: ${{ env.source-url }}
      env:
        NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'

    - name: Create the package
      run: dotnet pack --configuration Release -p:Version=${{ env.version }} -p:RepositoryUrl=${{ env.RepositoryUrl }}

    - name: Publish the package to GPR
      run: dotnet nuget push bin/Release/*.nupkg --source ${{ env.source-url }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.WRITE_PACKAGES_TOKEN }}
